export interface CalendarEvent {
  month: string;
  day: string;
  summary: string;
  link: string;
  date: string;
}

const pastEvents: CalendarEvent[] = [
  {
    month: 'Feb',
    day: '10',
    summary: 'Central Park Classic',
    link: 'https://www.bikereg.com/64054',
    date: '2024-02-10',
  },
  {
    month: 'Feb',
    day: '25',
    summary: 'Prospect Park Spring Classic',
    link: 'https://www.bikereg.com/64230',
    date: '2024-02-25',
  },
  {
    month: 'Apr',
    day: '13',
    summary: 'Beach Channel Bike Time Trial & Inline Skates',
    link: 'https://www.bikereg.com/64965',
    date: '2024-04-13',
  },
  {
    month: 'Apr',
    day: '27',
    summary: 'Atlantic Duathlon',
    link: 'https://runsignup.com/Race/NY/FarRockaway/AtlanticDuathlon',
    date: '2024-04-27',
  },
  {
    month: 'May',
    day: '12',
    summary: 'Coney Island Criterium (Road, Fixed, Skates)',
    link: 'https://www.bikereg.com/65211',
    date: '2024-05-12',
  },
  {
    month: 'May',
    day: '18',
    summary: 'Free Chariot Tournament',
    link: 'https://www.bikereg.com/65852',
    date: '2024-05-18',
  },
  {
    month: 'Jun',
    day: '29',
    summary: 'Free Chariot Tournament',
    link: 'https://www.bikereg.com/66169',
    date: '2024-06-29',
  },
  {
    month: 'Jul',
    day: '14',
    summary: 'Free Endurance Clinic & Races',
    link: 'https://www.bikereg.com/66835',
    date: '2024-07-14',
  },
  {
    month: 'Aug',
    day: '4',
    summary: "The Devil's Scratch (Kissena Velodrome)",
    link: 'https://www.bikereg.com/thedevilsscratch',
    date: '2024-08-04',
  },
  {
    month: 'Aug',
    day: '18',
    summary: 'East New York Criterium (Road, Fixed, Skates)',
    link: 'https://www.bikereg.com/64408',
    date: '2024-08-18',
  },
  {
    month: 'Sep',
    day: '22',
    summary: 'Diamond Mountain Classic Road Race',
    link: 'https://www.bikereg.com/diamondmountain',
    date: '2024-09-22',
  },
  {
    month: 'Sep',
    day: '22',
    summary: 'Diamond Mountain Time Trial',
    link: 'https://www.bikereg.com/dmtt',
    date: '2024-09-22',
  },
  {
    month: 'Sep',
    day: '29',
    summary: "Randall's Island Criterium (Road, Fixed, Skates)",
    link: 'https://www.bikereg.com/randalls',
    date: '2024-09-29',
  },
  {
    month: 'Oct',
    day: '13',
    summary: 'Atlantic Time Trial and Duathlon',
    link: 'https://www.bikereg.com/atlantictt',
    date: '2024-10-13',
  },
  {
    month: 'Oct',
    day: '26',
    summary: 'Breezy Time Trial & Inline Speed Skate 10K',
    link: 'https://www.bikereg.com/breezy',
    date: '2024-10-26',
  },
  {
    month: 'Oct',
    day: '27',
    summary: "The Devil's Scratch",
    link: 'https://www.bikereg.com/thedevilsscratch',
    date: '2024-10-27',
  },

  // Events for 2023
  {
    month: 'Feb',
    day: '26',
    summary: "Randall's Island Crit #1",
    link: 'https://www.bikereg.com/59086',
    date: '2023-02-26',
  },
  {
    month: 'Mar',
    day: '4',
    summary: "Randall's Island Crit #2",
    link: 'https://www.bikereg.com/59217',
    date: '2023-03-04',
  },
  {
    month: 'Mar',
    day: '18',
    summary: "Randall's Island Crit #3",
    link: 'https://www.bikereg.com/59640',
    date: '2023-03-18',
  },
  {
    month: 'Mar',
    day: '19',
    summary: "Randall's Island Crit #4",
    link: 'https://www.bikereg.com/59218',
    date: '2023-03-19',
  },
  {
    month: 'Apr',
    day: '8',
    summary: 'Prospect Park Spring Classic',
    link: 'https://www.bikereg.com/59920',
    date: '2023-04-08',
  },
  {
    month: 'Apr',
    day: '22',
    summary: 'First Responders Beach Channel TT (Bike & Inline Skate)',
    link: 'https://www.bikereg.com/59297',
    date: '2023-04-22',
  },
  {
    month: 'May',
    day: '6',
    summary: 'Central Park Spring Classic',
    link: 'https://www.bikereg.com/60687',
    date: '2023-05-06',
  },
  {
    month: 'Jul',
    day: '2',
    summary:
      "NYC Crits #1: Randall's Island Criterium (Road Bikes & Inline Skates)",
    link: 'https://www.bikereg.com/61098',
    date: '2023-07-02',
  },
  {
    month: 'Jul',
    day: '9',
    summary:
      "NYC Crits #2: Randall's Island Criterium Road and Fixed Gear Bikes",
    link: 'https://www.bikereg.com/61225',
    date: '2023-07-09',
  },
  {
    month: 'Jul',
    day: '22',
    summary: 'NYC Crits #3: North Woodmere Criterium',
    link: 'https://www.bikereg.com/61515',
    date: '2023-07-22',
  },
  {
    month: 'Jul',
    day: '23',
    summary:
      "NYC Crits #4: Randall's Island Criterium (Road Bikes & Inline Skates)",
    link: 'https://www.bikereg.com/61226',
    date: '2023-07-23',
  },
  {
    month: 'Aug',
    day: '20',
    summary: 'East New York Criterium',
    link: 'https://www.bikereg.com/61993',
    date: '2023-08-20',
  },
  {
    month: 'Mar',
    day: '5',
    summary: "Randall's Island Crit #1",
    link: 'https://www.bikereg.com/53755',
    date: '2022-03-05',
  },
  {
    month: 'Mar',
    day: '12',
    summary: "Randall's Island Crit #2",
    link: 'https://www.bikereg.com/54042',
    date: '2022-03-12',
  },
  {
    month: 'Mar',
    day: '20',
    summary: "Randall's Island Crit #3",
    link: 'https://www.bikereg.com/54043',
    date: '2022-03-20',
  },
  {
    month: 'Mar',
    day: '26',
    summary: "Randall's Island Crit #4",
    link: 'https://www.bikereg.com/54045',
    date: '2022-03-26',
  },
  {
    month: 'Apr',
    day: '9',
    summary: 'Prospect Park Circuit Race',
    link: 'https://www.bikereg.com/53953',
    date: '2022-04-09',
  },
  {
    month: 'May',
    day: '7',
    summary: 'Central Park Time Trial',
    link: 'https://www.bikereg.com/55299',
    date: '2022-05-07',
  },
  {
    month: 'May',
    day: '21',
    summary: 'Beach Channel Time Trial',
    link: 'https://www.bikereg.com/55243',
    date: '2022-05-21',
  },
  {
    month: 'Jul',
    day: '31',
    summary: 'Palisades Time Trial',
    link: 'https://www.bikereg.com/56621',
    date: '2022-07-31',
  },
  {
    month: 'Aug',
    day: '14',
    summary: 'Tour of Staten Island',
    link: 'https://www.bikereg.com/56442',
    date: '2022-08-14',
  },
  {
    month: 'Aug',
    day: '14',
    summary: 'Staten Island Time Trial',
    link: 'https://www.bikereg.com/56377',
    date: '2022-08-14',
  },
  {
    month: 'Aug',
    day: '28',
    summary: 'Central Park Classic',
    link: 'https://www.bikereg.com/56970',
    date: '2022-08-28',
  },
  {
    month: 'Oct',
    day: '9',
    summary: 'Central Park Time Trial',
    link: 'https://www.bikereg.com/57429',
    date: '2022-10-09',
  },
  {
    month: 'Oct',
    day: '15',
    summary: 'Beach Channel TT (Bike & Inline Skate)',
    link: 'https://www.bikereg.com/57668',
    date: '2022-10-15',
  },
  {
    month: 'Nov',
    day: '6',
    summary: 'Prospect Park Classic',
    link: 'https://www.bikereg.com/57464',
    date: '2022-11-06',
  },

  // Events for 2021
  {
    month: 'Mar',
    day: '28',
    summary: 'Central Park Time Trial',
    link: 'https://www.bikereg.com/49193',
    date: '2021-03-28',
  },
  {
    month: 'Apr',
    day: '3',
    summary: 'Prospect Park Time Trial',
    link: 'https://www.bikereg.com/49580',
    date: '2021-04-03',
  },
  {
    month: 'Apr',
    day: '17',
    summary: 'Beach Channel Time Trial #1',
    link: 'https://www.bikereg.com/50002',
    date: '2021-04-17',
  },
  {
    month: 'Apr',
    day: '24',
    summary: 'Beach Channel Time Trial #2',
    link: 'https://www.bikereg.com/50004',
    date: '2021-04-24',
  },
  {
    month: 'May',
    day: '1',
    summary: 'Beach Channel Time Trial #3',
    link: 'https://www.bikereg.com/50120',
    date: '2021-05-01',
  },
  {
    month: 'May',
    day: '2',
    summary: "Randall's Island Crit Spring Series #1",
    link: 'https://www.bikereg.com/50165',
    date: '2021-05-02',
  },
  {
    month: 'May',
    day: '9',
    summary: "Randall's Island Crit Spring Series #2",
    link: 'https://www.bikereg.com/50335',
    date: '2021-05-09',
  },
  {
    month: 'May',
    day: '16',
    summary: "Randall's Island Crit Spring Series #3",
    link: 'https://www.bikereg.com/50336',
    date: '2021-05-16',
  },
  {
    month: 'May',
    day: '22',
    summary: "World's Fair Race #1",
    link: 'https://www.bikereg.com/50424',
    date: '2021-05-22',
  },
  {
    month: 'May',
    day: '29',
    summary: "World's Fair Race #2",
    link: 'https://www.bikereg.com/50730',
    date: '2021-05-29',
  },
  {
    month: 'Jun',
    day: '5',
    summary: "Randall's Island Crit Spring Series #4",
    link: 'https://www.bikereg.com/50337',
    date: '2021-06-05',
  },
  {
    month: 'Jun',
    day: '6',
    summary: "World's Fair Race #3",
    link: 'https://www.bikereg.com/50742',
    date: '2021-06-06',
  },
  {
    month: 'Jun',
    day: '13',
    summary: "Last Minute Race @ Randall's Island",
    link: 'https://www.bikereg.com/51026',
    date: '2021-06-13',
  },
  {
    month: 'Jun',
    day: '26',
    summary: "World's Fair Race #4",
    link: 'https://www.bikereg.com/50990',
    date: '2021-06-26',
  },
  {
    month: 'Jul',
    day: '11',
    summary: "Randall's Island Crit Summer Series #1",
    link: 'https://www.bikereg.com/51143',
    date: '2021-07-11',
  },
  {
    month: 'Jul',
    day: '24',
    summary: "Randall's Island Crit Summer Series #2",
    link: 'https://www.bikereg.com/51144',
    date: '2021-07-24',
  },
  {
    month: 'Aug',
    day: '1',
    summary: "Randall's Island Crit Summer Series #3",
    link: 'https://www.bikereg.com/51145',
    date: '2021-08-01',
  },
  {
    month: 'Aug',
    day: '15',
    summary: "Randall's Island Crit Summer Series #4",
    link: 'https://www.bikereg.com/51432',
    date: '2021-08-15',
  },
  {
    month: 'Sep',
    day: '25',
    summary: "World's Fair Race #6",
    link: 'https://www.bikereg.com/52119',
    date: '2021-09-25',
  },
  {
    month: 'Oct',
    day: '10',
    summary: "World's Fair Race #7",
    link: 'https://www.bikereg.com/52120',
    date: '2021-10-10',
  },
  {
    month: 'Oct',
    day: '16',
    summary: "World's Fair Race #8",
    link: 'https://www.bikereg.com/52121',
    date: '2021-10-16',
  },
  {
    month: 'Oct',
    day: '23',
    summary: 'Beach Channel Time Trial',
    link: 'https://www.bikereg.com/52552',
    date: '2021-10-23',
  },
  {
    month: 'Oct',
    day: '31',
    summary: "Trick or Treat @ Randall's Crit",
    link: 'https://www.bikereg.com/52410',
    date: '2021-10-31',
  },

  // Events for 2020
  {
    month: 'Feb',
    day: '29',
    summary: 'Wards Island Crit (Fixed Gear Bikes) #1',
    link: 'https://www.bikereg.com/45647',
    date: '2020-02-29',
  },
  {
    month: 'Feb',
    day: '29',
    summary: "Randall's Island Crit (Road Bikes) #1",
    link: 'https://www.bikereg.com/45646',
    date: '2020-02-29',
  },
  {
    month: 'Mar',
    day: '7',
    summary: 'Wards Island Crit (Fixed Gear Bikes) #2',
    link: 'https://www.bikereg.com/46309',
    date: '2020-03-07',
  },
  {
    month: 'Mar',
    day: '7',
    summary: "Randall's Island Crit (Road Bikes) #2",
    link: 'https://www.bikereg.com/46311',
    date: '2020-03-07',
  },
  {
    month: 'Mar',
    day: '15',
    summary: 'Wards Island Crit (Fixed Gear Bikes) #3',
    link: 'https://www.bikereg.com/46310',
    date: '2020-03-15',
  },
  {
    month: 'Mar',
    day: '15',
    summary: "Randall's Island Crit (Road Bikes) #3",
    link: 'https://www.bikereg.com/46312',
    date: '2020-03-15',
  },
  {
    month: 'May',
    day: '30',
    summary: 'Free Post-Apocalyptic Individual Time Trial',
    link: 'https://www.bikereg.com/47376',
    date: '2020-05-30',
  },
  {
    month: 'Jun',
    day: '20',
    summary: 'Free Post-Apocalyptic Individual Time Trial',
    link: 'https://www.bikereg.com/47483',
    date: '2020-06-20',
  },
  {
    month: 'Sep',
    day: '19',
    summary: 'Free Beach Channel Time Trial',
    link: 'https://www.bikereg.com/48039',
    date: '2020-09-19',
  },
  {
    month: 'Oct',
    day: '3',
    summary: 'Beach Channel Time Trial #1',
    link: 'https://www.bikereg.com/48221',
    date: '2020-10-03',
  },
  {
    month: 'Oct',
    day: '17',
    summary: 'Beach Channel Time Trial #2',
    link: 'https://www.bikereg.com/48266',
    date: '2020-10-17',
  },
  {
    month: 'Oct',
    day: '31',
    summary: 'Beach Channel Time Trial #3',
    link: 'https://www.bikereg.com/48272',
    date: '2020-10-31',
  },

  // Events for 2019
  {
    month: 'Mar',
    day: '3',
    summary: "Randall's Island Crit Sunday Series (Road Bikes)",
    link: 'https://www.bikereg.com/41449',
    date: '2019-03-03',
  },
  {
    month: 'Mar',
    day: '12',
    summary: "Randall's Island Crit Tuesday Series (Road Bikes)",
    link: 'https://www.bikereg.com/41491',
    date: '2019-03-12',
  },
  {
    month: 'Mar',
    day: '12',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/41505',
    date: '2019-03-12',
  },
  {
    month: 'Mar',
    day: '17',
    summary: "Randall's Island Crit Sunday Series (Road Bikes)",
    link: 'https://www.bikereg.com/41751',
    date: '2019-03-17',
  },
  {
    month: 'Mar',
    day: '19',
    summary: "Randall's Island Crit Tuesday Series (Road Bikes)",
    link: 'https://www.bikereg.com/41755',
    date: '2019-03-19',
  },
  {
    month: 'Mar',
    day: '19',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/41752',
    date: '2019-03-19',
  },
  {
    month: 'Mar',
    day: '26',
    summary: "Randall's Island Crit Tuesday Series (Road Bikes)",
    link: 'https://www.bikereg.com/41757',
    date: '2019-03-26',
  },
  {
    month: 'Mar',
    day: '26',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/41753',
    date: '2019-03-26',
  },
  {
    month: 'Apr',
    day: '2',
    summary: "Randall's Island Crit Tuesday Series (Road Bikes)",
    link: 'https://www.bikereg.com/41758',
    date: '2019-04-02',
  },
  {
    month: 'Apr',
    day: '2',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/41754',
    date: '2019-04-02',
  },
  {
    month: 'Jul',
    day: '4',
    summary: "Randall's Island Crit Weekend Series",
    link: 'https://www.bikereg.com/43057',
    date: '2019-07-04',
  },
  {
    month: 'Jul',
    day: '7',
    summary: "Randall's Island Crit Weekend Series",
    link: 'https://www.bikereg.com/42743',
    date: '2019-07-07',
  },
  {
    month: 'Jul',
    day: '9',
    summary: "Randall's Island Crit Weekday Series (Road Bikes)",
    link: 'https://www.bikereg.com/42929',
    date: '2019-07-09',
  },
  {
    month: 'Jul',
    day: '9',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/42932',
    date: '2019-07-09',
  },
  {
    month: 'Jul',
    day: '11',
    summary: "Randall's Island Crit Weekday Series (Road Bikes)",
    link: 'https://www.bikereg.com/43218',
    date: '2019-07-11',
  },
  {
    month: 'Jul',
    day: '11',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/43213',
    date: '2019-07-11',
  },
  {
    month: 'Jul',
    day: '21',
    summary: "Randall's Island Crit Weekday Series (Road Bikes)",
    link: 'https://www.bikereg.com/43332',
    date: '2019-07-21',
  },
  {
    month: 'Jul',
    day: '27',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/43409',
    date: '2019-07-27',
  },
  {
    month: 'Aug',
    day: '4',
    summary: "Randall's Island Crit Weekend Series",
    link: 'https://www.bikereg.com/43058',
    date: '2019-08-04',
  },
  {
    month: 'Aug',
    day: '11',
    summary: "Randall's Island Crit Weekend Series",
    link: 'https://www.bikereg.com/43059',
    date: '2019-08-11',
  },
  {
    month: 'Aug',
    day: '15',
    summary: "Randall's Island Crit Weekday Series (Road Bikes)",
    link: 'https://www.bikereg.com/43222',
    date: '2019-08-15',
  },
  {
    month: 'Aug',
    day: '15',
    summary: 'Wards Island Crit Series (Fixed Gear Bikes)',
    link: 'https://www.bikereg.com/43217',
    date: '2019-08-15',
  },

  // Events for 2018
  {
    month: 'Jul',
    day: '1',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Weekend Points Series',
    link: 'https://www.bikereg.com/39341',
    date: '2018-07-01',
  },
  {
    month: 'Jul',
    day: '7',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Weekend Points Series',
    link: 'https://www.bikereg.com/39376',
    date: '2018-07-07',
  },
  {
    month: 'Jul',
    day: '14',
    summary: 'Road & Fixed Gear Criterium @ Wards Island Circuit',
    link: 'https://www.bikereg.com/39477',
    date: '2018-07-14',
  },
  {
    month: 'Jul',
    day: '15',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Weekend Points Series',
    link: 'https://www.bikereg.com/39377',
    date: '2018-07-15',
  },
  {
    month: 'Jul',
    day: '21',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Weekend Points Series',
    link: 'https://www.bikereg.com/39378',
    date: '2018-07-21',
  },
  {
    month: 'Aug',
    day: '2',
    summary: 'Thursday $20 Sprints Series by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39344',
    date: '2018-08-02',
  },
  {
    month: 'Aug',
    day: '9',
    summary: 'Thursday $20 Sprints Series by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39649',
    date: '2018-08-09',
  },
  {
    month: 'Aug',
    day: '16',
    summary: 'Thursday $20 Sprints Series by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39651',
    date: '2018-08-16',
  },
  {
    month: 'Aug',
    day: '23',
    summary: 'Thursday $20 Sprints Series by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39653',
    date: '2018-08-23',
  },
  {
    month: 'Aug',
    day: '25',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Saturday Points Series',
    link: 'https://www.bikereg.com/39842',
    date: '2018-08-25',
  },
  {
    month: 'Aug',
    day: '25',
    summary: 'Wards Island Circuit Criterium by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39896',
    date: '2018-08-25',
  },
  {
    month: 'Aug',
    day: '30',
    summary: 'Thursday $20 Sprints Series by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39654',
    date: '2018-08-30',
  },
  {
    month: 'Sep',
    day: '1',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Saturday Points Series',
    link: 'https://www.bikereg.com/39912',
    date: '2018-09-01',
  },
  {
    month: 'Sep',
    day: '3',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Saturday Points Series',
    link: 'https://www.bikereg.com/40002',
    date: '2018-09-03',
  },
  {
    month: 'Sep',
    day: '6',
    summary: 'Thursday $20 Sprints Series by DisTRACtion Circus',
    link: 'https://www.bikereg.com/39655',
    date: '2018-09-06',
  },
  {
    month: 'Sep',
    day: '8',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Saturday Points Series',
    link: 'https://www.bikereg.com/39987',
    date: '2018-09-08',
  },
  {
    month: 'Sep',
    day: '22',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Saturday Points Series',
    link: 'https://www.bikereg.com/40003',
    date: '2018-09-22',
  },
  {
    month: 'Sep',
    day: '29',
    summary:
      'Verrazano Bicycle Shop p/b DisTRACtion Circus Saturday Points Series',
    link: 'https://www.bikereg.com/40004',
    date: '2018-09-29',
  },
];

export default pastEvents;
